config/routes.rb
Rails.application.routes.draw do
  devise_for :hairstylists, controllers: {
    sessions: 'hairstylists/sessions',
    passwords: 'hairstylists/passwords',
    registrations: 'hairstylists/registrations'
  }
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'top_pages#home'
  resources :users
  resources :hairstylists
  scope :hairstylists do
    resources :hairstyleposts, only: [:show, :destroy, :update]
  end
  resources :hairstyleposts
  get 'tags/:tag', to: 'hairstyleoposts#index', as: :tag
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def home
    @hairstylepost = current_hairstylist.hairstyleposts.build if hairstylist_signed_in?
    # @hairstyleposts = Hairstylepost.paginate(page: params[:page]).search(params[:search])
  end
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/top_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>ChokiChoki Beauty</h1>
<h2>
  Welcome to ChokiChoki Beauty!
</h2>
<div class="top_page">
<% if hairstylist_signed_in? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "新しいヘアスタイルを投稿する", new_hairstylepost_path, class: "btn btn-lg btn-primary" %>
      <%#section class="micropost_form"%>
        <%#= render 'shared/hairstylepost_form' %>
      <%#/section%>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="btn">
        <li><%= link_to "掲載をご希望のスタイリストはこちら", new_hairstylist_registration_path, class: "btn btn-lg btn-primary" %></li>
        <li><%= link_to "お気に入りのヘアスタイルを探す", hairstyleposts_path, method: :get, class: "btn btn-lg btn-primary" %></li>
      </ul>
    </div>
  </div>
<% end %> 
</div>