config/routes.rb
Rails.application.routes.draw do
  devise_for :hairstylists, controllers: {
    sessions: 'hairstylists/sessions',
    passwords: 'hairstylists/passwords',
    registrations: 'hairstylists/registrations'
  }
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'top_pages#home'
  resources :users
  resources :hairstylists
  scope :hairstylists do
    resources :hairstyleposts, only: [:show, :destroy, :update]
  end
  resources :hairstyleposts
  get 'tags/:tag', to: 'hairstyleoposts#index', as: :tag
end

app/models/hairstylepost.rb
class Hairstylepost < ApplicationRecord
  acts_as_taggable
  belongs_to :hairstylist
  has_many :hairstylepictures, dependent: :destroy
  accepts_nested_attributes_for :hairstylepictures, allow_destroy: true
  default_scope -> { order(created_at: :desc) }
  validates :hairstylist_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  #validates :picture, presence: true
  #mount_uploader :picture, PictureUploader

  def self.search(search)
    return Hairstylepost.all unless search
    #Hairstylepost.where(['content LIKE ?', "%#{search}%"]) #検索とcontentの部分一致を表示
    Hairstylepost.tagged_with("#{search}") #acts_as_taggable_on gem で検索で使えるtagged_withメソッド
  end
end

app/controllers/hairstyleposts_controller.rb
class HairstylepostsController < ApplicationController
  before_action :authenticate_hairstylist!, only: [:create, :update, :destroy]
  before_action :correct_hairstylist, only: [:edit, :update, :destroy]

  def index
    if params[:search].present?
      @hairstyleposts = Hairstylepost.paginate(page: params[:page]).tagged_with( params[:search], :any => true )
      if @hairstyleposts.blank?
        flash[:alert] = "該当するヘアスタイルがありません"
        @hairstyleposts = Hairstylepost.all
      end
    else
      @hairstyleposts = Hairstylepost.all
    end
  end

  def show
    @hairstylepost = Hairstylepost.find(params[:id])
  end

  def new
    @hairstylepost = Hairstylepost.new
    @hairstylepictures = @hairstylepost.hairstylepictures.build
  end

  def edit
    @hairstylepost = Hairstylepost.find(params[:id])
  end

  def create
    @hairstylepost = current_hairstylist.hairstyleposts.build(hairstylepost_params)
    if @hairstylepost.save
      flash[:success] = "hairstylepost created!"
      redirect_to hairstylist_path(current_hairstylist)
    else
      render 'top_pages/home'
    end
  end

  def update
    @hairstylepost = Hairstylepost.find_by(id: params[:id])
    #  @hairstylepost.title = params[:title]
    if @hairstylepost.update_attributes(hairstylepost_update_params)
    #  if @hairstylepost.save
      flash[:success] = "hairstylepost updated!"
      redirect_to hairstylist_path(current_hairstylist)
    else
      render 'top_pages/home'
    end
  end

  def destroy
    @hairstylepost.destroy
    flash[:success] = "Hairstylepost deleted"
    #  redirect_to request.referrer || root_url
    redirect_to hairstylist_path(current_hairstylist)
  end

  private

    def hairstylepost_params
      params.require(:hairstylepost).permit(:picture, :title, :description, tag_list:[],
      hairstylepictures_attributes: [:picture_url])
    end

    def hairstylepost_update_params
      params.require(:hairstylepost).permit(:picture, :title, :description, tag_list:[],
      hairstylepictures_attributes: [:picture_url, :_destroy, :id])
    end

    def correct_hairstylist
      @hairstylepost = current_hairstylist.hairstyleposts.find_by(id: params[:id])
      redirect_to root_url if @hairstylepost.nil?
    end
end

app/helpers/hairstyleposts_helper.rb
module HairstylepostsHelper
end

app/views/hairstyleposts/_hairstylepost.html.erb
<li id="micropost-<%= hairstylepost.id %>">
  <span class="content">
    <%= link_to "/hairstyleposts/#{hairstylepost.id}" do %>
    <%#= link_to hairstylepost_path(current_hairstylepost) do %>
      <%#= hairstylepost.hairstylepictures.each do |hairstylepicture| %>
        <%#= image_tag hairstylepicture.picture_url.url if hairstylepicture.picture_url.present? %>
      <%# end %>
    <%= image_tag (hairstylepost.hairstylepictures[0].picture_url.url if hairstylepost.hairstylepictures.present?), size:'300x400' %>
    <%#= image_tag hairstylepost.hairstylepictures.picture_url %>
    <h2><%#= hairstylepost.title %></h2>
    <%#= hairstylepost.description %>
    <% end %>
  </span>
  <span class="timestamp">
    <%# Posted <%= time_ago_in_words(hairstylepost.created_at) %> <%# ago. %>
    <% if current_hairstylist?(hairstylepost.hairstylist) %>
      <%= link_to "投稿を編集", "/hairstyleposts/#{hairstylepost.id}/edit" %>
      <%= link_to "投稿を削除", hairstylepost, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/hairstyleposts/edit.html.erb
<% provide(:title, "Edit hairstylepost") %>
<h1>投稿したヘアスタイルを編集する</h1>

<!--
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/hairstylepost_form' %>
  </div>
</div>
-->


<div class="main">
  <section class="main__block">
    <%= form_with model:@hairstylepost, local:true do |f| %>
      <h2 class="sell__block__head">
        ヘアスタイルを編集する
      </h2>
      <div class="sell__block__form">
        <div class="sell__block__form__upload">
          <h3 class="sell__block__form__upload__head">
            ヘアスタイル画像
            <span class="require">必須</span>
          </h3>
          <p>最大５枚までアップロードできます</p>
          <div class="post__drop__box__container">
            <div class="prev-content">
            <!--JSで挿入したhtmlと同じ形　each文でのプレビュー表示 -->
              <% @hairstylepost.hairstylepictures.each do |hairstylepicture| %>
                <div class="preview-box">
                  <div class="upper-box">
                    <%= image_tag hairstylepicture.picture_url.url, width: "112", height: "112", alt: "preview" %>
                  </div>
                  <div class="lower-box">
                    <!--
                    <div class="update-box">
                      <label class="edit-btn">編集</label>
                    </div>
                    -->
                    <div class="delete-box">
                      <div class="delete-btn">
                        <span>削除</span>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="label-content">
            <!--プレビューの数に合わせてforオプションを指定 -->
              <%= f.label :"hairstylepictures_attributes_#{@hairstylepost.hairstylepictures.length}_picture_url", class: "label-box", id: "label-box--#{@hairstylepost.hairstylepictures.length}" do %>
                <pre class="label-box__text-visible">クリックして画像をアップロード</pre>
              <% end %>
            </div>
            <div class="hidden-content">
              <!--プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置 -->
              <%= f.fields_for :hairstylepictures do |i| %>
                <%= i.file_field :picture_url, class: "hidden-field" %>
                <%= i.check_box:_destroy, class: "hidden-checkbox" %>
              <% end %>
              <!-- 5つのfile_fieldを準備するに当たって、足りない分を表示 -->
              <% @hairstylepost.hairstylepictures.length.upto(4) do |i| %>
                <input class="hidden-field" id="hairstylepost_hairstylepictures_attributes_<%= i %>_picture_url" name="hairstylepost[hairstylepictures_attributes][<%= i %>][picture_url]" type="file"></input>
              <% end %>
            </div>
          </div>
        </div>
        <div class="sell__block__form__name">
          <div class="form-group__name">
            <label>
              ヘアスタイルタイトル
              <span class="require">必須</span>
            </label>
            <div>
              <%= f.text_field :title, placeholder:"タイトル", class: "form__group__name" %>
            </div>
          </div>
          <div class="form-group__name">
            <label>
              ヘアスタイルの詳細説明
              <span class="require">必須</span>
            </label>
            <div>
              <%= f.text_area :description, placeholder:"ヘアスタイルの詳細説明を編集",class: "form__group__name" %>
            </div>
          </div>
          <div class="form-group__name">
            <label>
              タグ
              <span class="require">必須</span>
            </label>
            <div>
              <%= f.text_field :tag_list, value: @hairstylepost.tag_list.join(','), class: "form-control" %></br>
            </div>
          </div>
        </div>
        <div class="sell__block__form__btn">
        <div>
          <%= f.submit "post",class: "btn-default__btn-red" %>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/hairstyleposts/index.html.erb
<div class="row">
<div class="col-md-12">
<h1>ヘアスタイルを探す</h1>
<%= form_tag hairstyleposts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %> 

<ol class="microposts">

  <%= render @hairstyleposts %>

</ol>
</div>
</div>

app/views/hairstyleposts/new.html.erb
<div class="main">
  <section class="main__block">
    <%= form_with model:@hairstylepost, local:true do |f| %>
      <h2 class="sell__block__head">
      新しいヘアスタイルを投稿する
      </h2>
      <div class="sell__block__form">
        <div class="sell__block__form__upload">
          <h4 class="sell__block__form__upload__head">
          ヘアスタイル画像
            <span class="require">必須</span>
          </h4>
          <p>最大５枚までアップロードできます</p>
          <div class="post__drop__box__container">
            <div class="prev-content"></div>
            <div class="label-content">
              <label class="label-box" for="hairstylepost_hairstylepictures_attributes_0_picture_url" id="label-box--0">
                <pre class="label-box__text-visible">クリックして画像をアップロード</pre>
              </label>
            </div>
            <div class="hidden-content">
              <%= f.fields_for :hairstylepictures do |i| %>
                <%= i.file_field :picture_url, class: "hidden-field" %>
                <input class="hidden-field" id="hairstylepost_hairstylepictures_attributes_1_picture_url" name="hairstylepost[hairstylepictures_attributes][1][picture_url]" type="file"></input>
                <input class="hidden-field" id="hairstylepost_hairstylepictures_attributes_2_picture_url" name="hairstylepost[hairstylepictures_attributes][2][picture_url]" type="file"></input>
                <input class="hidden-field" id="hairstylepost_hairstylepictures_attributes_3_picture_url" name="hairstylepost[hairstylepictures_attributes][3][picture_url]" type="file"></input>
                <input class="hidden-field" id="hairstylepost_hairstylepictures_attributes_4_picture_url" name="hairstylepost[hairstylepictures_attributes][4][picture_url]" type="file"></input>
              <% end %>
            </div>
          </div>
        </div>
        <div class="sell__block__form__name">
          <div class="form-group__name">
            <label>
              ヘアスタイルタイトル
              <span class="require">必須</span>
            </label>
            <div>
              <%= f.text_field :title, placeholder:"タイトル",class: "form__group__name" %>
            </div>
          </div>
          <div class="form-group__name">
            <label>
              ヘアスタイルの詳細説明
              <span class="require">必須</span>
            </label>
            <div>
              <%= f.text_area :description, placeholder:"ヘアスタイルの詳細説明を記入してください",class: "form__group__name" %>
            </div>
          </div>
          <div class="form-group__name">
            <label>
              タグ
              <span class="require">必須【複数タグをつける際は「,」（半角コンマ）で区切って記入してください】</span>
            </label>
            <div>
              <%= f.text_field :tag_list, value: @hairstylepost.tag_list.join(','), class: "form-control" %></br>
            </div>
          </div>
        </div>
        <div class="sell__block__form__btn">
          <div>
            <%= f.submit "投稿する",class: "btn-default__btn-red" %>
          </div>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/hairstyleposts/show.html.erb
<div id="micropost-<%= @hairstylepost.id %>">
  <div class="details">
    <ul class="img" >
      <% @hairstylepost.hairstylepictures.each do |hairstylepicture| %>
        <li>
        <%= image_tag (hairstylepicture.picture_url.url if hairstylepicture.picture_url.present?), size:'300x400' %>
        </li>
      <% end %>
      <%#= image_tag @hairstylepost.hairstylepictures.first.picture_url.url if @hairstylepost.hairstylepictures.first.picture_url? %>
    </div>
    <h2><%= @hairstylepost.title %></h2>
    <h3><%= @hairstylepost.description %></h3>
  </div>
  <span class="timestamp">
  　Posted <%= time_ago_in_words(@hairstylepost.created_at) %> ago.
    <% if current_hairstylist?(@hairstylepost.hairstylist) %>
      <%= link_to "投稿を編集", "/hairstyleposts/#{@hairstylepost.id}/edit" %>
      <%= link_to "投稿を削除", @hairstylepost, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  <div class="profile-link">
    <%= link_to "スタイリスト情報を確認して予約する","/hairstylists/#{@hairstylepost.hairstylist.id}", class: "btn btn-lg btn-primary" %>
  </div>
</div>