config/routes.rb
Rails.application.routes.draw do
  devise_for :hairstylists, controllers: {
    sessions: 'hairstylists/sessions',
    passwords: 'hairstylists/passwords',
    registrations: 'hairstylists/registrations'
  }
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'top_pages#home'
  resources :users
  resources :hairstylists
  scope :hairstylists do
    resources :hairstyleposts, only: [:show, :destroy, :update]
  end
  resources :hairstyleposts
  get 'tags/:tag', to: 'hairstyleoposts#index', as: :tag
end

app/views/layouts/_footer.html.erb
<footer class="footer">  
  <small>
    The <a href="https://railstutorial.jp/">ChokiChoki Beauty</a>
    by <a href="https://camp.potepan.com/">Hiroya Mizuno</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ChokiChoki Beauty", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "ヘアスタイルを探す", hairstyleposts_path, method: :get %></li>
            <% if user_signed_in? %>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 アカウント設定 <b class="caret"></b>
               </a>
               <ul class="dropdown-menu">
                 <li><%= link_to "ユーザープロフィール", current_user %></li>
                 <li><%= link_to "ユーザー情報詳細設定", edit_user_registration_path(current_user) %></li>
                 <li class="divider"></li>
                 <li>
                   <%= link_to "ユーザーログアウト", destroy_user_session_path, method: :delete %>
                 </li>
               </ul>
             </li>
            <% else %>
              <li><%= link_to "ユーザーログイン", new_user_session_path %></li>
            <% end %>
            <% if hairstylist_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  アカウント設定 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "スタイリスト情報", current_hairstylist %></li>
                  <li><%= link_to "スタイリスト情報を編集する", edit_hairstylist_path(current_hairstylist) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "スタイリストログアウト", destroy_hairstylist_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "スタイリストログイン", new_hairstylist_session_path %></li>
            <% end %>
            <% if hairstylist_signed_in? %>
              <li><%= link_to "ヘアスタイルを投稿する", new_hairstylepost_path %></li>
            <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
 <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
 </script>
<![endif]-->

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    
  </body>
</html>